# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beaver < Formula
  desc ""
  homepage "https://github.com/amalshaji/beaver"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amalshaji/beaver/releases/download/0.2.0/beaver_0.2.0_Darwin_x86_64.zip"
      sha256 "492094442ed0cc7aafdea374d2701a590c2e0d2ebd1c830334cb1fbd114f24d1"

      def install
        bin.install "beaver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amalshaji/beaver/releases/download/0.2.0/beaver_0.2.0_Darwin_arm64.zip"
      sha256 "07ac8eb8898ac43e73d3f27890eb7600efd77d8b69acdace3d81c3108cdd67b5"

      def install
        bin.install "beaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amalshaji/beaver/releases/download/0.2.0/beaver_0.2.0_Linux_arm64.zip"
      sha256 "20b82c1c7e0771f638aeeeda16b1b749f8719948faef9bb64f0dd2f25c2ca33f"

      def install
        bin.install "beaver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amalshaji/beaver/releases/download/0.2.0/beaver_0.2.0_Linux_x86_64.zip"
      sha256 "ac379af77fc272ba741db6ec3ae6d00f0aea8496a78471ced9426be76ed06096"

      def install
        bin.install "beaver"
      end
    end
  end
end
