# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portr < Formula
  desc ""
  homepage "https://github.com/amalshaji/portr"
  version "0.0.21-beta"

  on_macos do
    on_intel do
      url "https://github.com/amalshaji/portr/releases/download/0.0.21-beta/portr_0.0.21-beta_Darwin_x86_64.zip"
      sha256 "430f3baa31fd32cdbccb32b983d01cf091fc732d6eda65acab4827ad069bacf2"

      def install
        bin.install "portr"
      end
    end
    on_arm do
      url "https://github.com/amalshaji/portr/releases/download/0.0.21-beta/portr_0.0.21-beta_Darwin_arm64.zip"
      sha256 "521f6491037209f5052cc5c18e10821902150f84179dd6e965584376247f9378"

      def install
        bin.install "portr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amalshaji/portr/releases/download/0.0.21-beta/portr_0.0.21-beta_Linux_x86_64.zip"
        sha256 "c042f316364fcbadd2174aa9dc0da30242fd3cf504fffa867579be74acbd16f3"

        def install
          bin.install "portr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amalshaji/portr/releases/download/0.0.21-beta/portr_0.0.21-beta_Linux_arm64.zip"
        sha256 "06a31a52c98ef82e017cf46838dd919a9c929d568e51107c0d3fc0f75f189cc1"

        def install
          bin.install "portr"
        end
      end
    end
  end
end
