# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portr < Formula
  desc ""
  homepage "https://github.com/amalshaji/portr"
  version "0.0.37-beta"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amalshaji/portr/releases/download/0.0.37-beta/portr_0.0.37-beta_Darwin_x86_64.zip"
      sha256 "475de7a31d9a7884dd3eaa33cae7e976e5d71f93966d5794aee6213b1c7abf6a"

      def install
        bin.install "portr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amalshaji/portr/releases/download/0.0.37-beta/portr_0.0.37-beta_Darwin_arm64.zip"
      sha256 "ea67558db1078eb9badd7ed107faa50b5d9cc338eeb8ce5f9bec36c908182d15"

      def install
        bin.install "portr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amalshaji/portr/releases/download/0.0.37-beta/portr_0.0.37-beta_Linux_x86_64.zip"
        sha256 "a697bf0fe8bf46bc93f746d846a6ce0a50f1f58617699c64796e59d7016e300a"

        def install
          bin.install "portr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/amalshaji/portr/releases/download/0.0.37-beta/portr_0.0.37-beta_Linux_arm64.zip"
        sha256 "2013bbcafb62d69fe2dc886b4257efc7fc7da0a9194b89322ae75fd44a5369d8"

        def install
          bin.install "portr"
        end
      end
    end
  end
end
