# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portr < Formula
  desc ""
  homepage "https://github.com/amalshaji/portr"
  version "1.0.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amalshaji/portr/releases/download/v1.0.18/portr_1.0.18_Darwin_x86_64.zip"
      sha256 "7ceca11400b4ff8b2db2cab41411019ce35f66687825704562fe62c428a104a2"

      define_method(:install) do
        bin.install "portr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amalshaji/portr/releases/download/v1.0.18/portr_1.0.18_Darwin_arm64.zip"
      sha256 "d90a79991336187d302f5c91cbce7aa292cf59713d3d1b72b345d111b978ef70"

      define_method(:install) do
        bin.install "portr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amalshaji/portr/releases/download/v1.0.18/portr_1.0.18_Linux_x86_64.zip"
      sha256 "e92aa2b1bc2ea2bc7fa13b79f595d3588c501e983e26659bf5df3705b9d7d807"
      define_method(:install) do
        bin.install "portr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amalshaji/portr/releases/download/v1.0.18/portr_1.0.18_Linux_arm64.zip"
      sha256 "faeb65f6a4183f3022cc4e70b28952332d1656a1482e0c4bad43b998595dc9b6"
      define_method(:install) do
        bin.install "portr"
      end
    end
  end
end
