# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcproxy < Formula
  desc "A TCP proxy for PostgreSQL connections with SSH tunnel support"
  homepage "https://github.com/amalshaji/tcproxy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amalshaji/tcproxy/releases/download/0.1.0/tcproxy_0.1.0_Darwin_x86_64.zip"
      sha256 "d4aef67fdf4e5fb71a8b4fb1285ccf9136d66578dda87125f65a4da4f3ebd055"

      def install
        bin.install "tcproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amalshaji/tcproxy/releases/download/0.1.0/tcproxy_0.1.0_Darwin_arm64.zip"
      sha256 "f1520124b094983f10ad238417082271fea4b8f3074657b10854fe5062728def"

      def install
        bin.install "tcproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/amalshaji/tcproxy/releases/download/0.1.0/tcproxy_0.1.0_Linux_x86_64.zip"
      sha256 "32a7184d5a0ded96981d729dab80ccd0a2d2c50d09581480e0319623cf48acb8"
      def install
        bin.install "tcproxy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/amalshaji/tcproxy/releases/download/0.1.0/tcproxy_0.1.0_Linux_arm64.zip"
      sha256 "d6d7463497bff285b7c7d815eec8f7ccf0e651f0227483bb31f699580fe03078"
      def install
        bin.install "tcproxy"
      end
    end
  end
end
